language: generic
dist: trusty

matrix:
  include:
  - name: "Python 3.6 on Linux"
    os: linux
    env: CONDA=3.6
  - name: "Python 3.6 on Mac OS"
    os: osx
    env: CONDA=3.6
    
before_install:
- |
  if [ -n "$CONDA" ]; then
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64; fi
    wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no
    conda config --add channels conda-forge
    conda update -q conda
    conda install -q conda-build
    conda create -q -n test-environment python=$CONDA pip
    conda activate test-environment
  fi
  
install:
- |
  if [ -n "$CONDA" ]; then
    conda install -c conda-forge --file requirements.txt
    pip install -e .
  fi

script:
- pytest --cov-report term-missing --cov=src/kanapy tests/

after_success:
- codecov

notifications:
  email: false


